# Generated by Django 3.2.8 on 2021-10-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='espn_s2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='league_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='league',
            name='swid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='espn_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='espn_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='points_for',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='victory_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
