# Generated by Django 3.2.8 on 2021-11-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0003_matchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='away_vp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_vp',
            field=models.IntegerField(default=0),
        ),
    ]
